from .core import run, get_logger, cmd_is_available
from .project import Project
import os

class JavaCompiler:
    def __init__(self, project: Project):
        self.tools = os.path.abspath("./build_logic/tools")
        self.aapt2 = os.path.join(self.tools, "aapt2")
        self.android_jar = os.path.join(self.tools, "android.jar")
        self.project = project
    
    def prepare(self):
        pass
    
    def start(self):
        get_logger().info("> :app:compileJavaWithJavac")

        java_available = cmd_is_available("javac")
        if not java_available:
            get_logger().error("> javac not detected in PATH. Please set it in PATH.")
            return
    
        java_classes_dir = self.project.get_java_classes_dir()
        os.makedirs(java_classes_dir, exist_ok=True)
        
        java_files = self.project.find_java_files()
        java_r_files = self.project.find_java_files(self.project.get_gen_dir())
        if not java_r_files:
            get_logger().error("> No java files generated by AAPT2")
            return
        
        java_files.extend(java_r_files)
        
        lib_jars = self.project.find_lib_jars()
        classpath = os.pathsep.join([
            self.android_jar,
            *lib_jars
        ])

        
        args = [
            "javac",
            "-source", "17",
            "-target", "17",
            "-classpath", classpath,
            "-nowarn",
            "-proc:none",
            "-d", self.project.get_java_classes_dir(),
            *java_files
        ]
        
        run(args)
